# Generated by Django 5.2.12 on 2026-03-18 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi', '0006_order_shipping_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
