# Generated by Django 5.2.12 on 2026-03-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi', '0009_remove_orderitem_status_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
