# Generated by Django 5.2.12 on 2026-03-21 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multi', '0012_activity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='action_type',
            new_name='activity_type',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='user',
        ),
    ]
