# Generated by Django 5.2.12 on 2026-03-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi', '0014_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='message_type',
            field=models.CharField(choices=[('contact', 'Contact'), ('support', 'Support'), ('report', 'Report')], default='contact', max_length=20),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('unread', 'Unread'), ('read', 'Read'), ('resolved', 'Resolved')], default='unread', max_length=20),
        ),
    ]
