# Generated by Django 5.2.13 on 2026-04-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi', '0015_contactmessage_message_type_contactmessage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='seller_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
