# Generated by Django 5.2.15 on 2026-07-05 23:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi', '0020_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispute',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='dispute',
            old_name='evidence',
            new_name='admin_decision',
        ),
        migrations.AddField(
            model_name='dispute',
            name='admin_decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispute',
            name='admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispute',
            name='buyer_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispute',
            name='buyer_declaration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dispute',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispute_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispute',
            name='dispute_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='dispute',
            name='reason',
            field=models.CharField(choices=[('wrong_item', 'Wrong Item Received'), ('damaged', 'Damaged Product'), ('counterfeit', 'Counterfeit Product'), ('missing_accessories', 'Missing Accessories'), ('not_as_described', 'Product Not As Described'), ('not_delivered', 'Item Not Delivered'), ('other', 'Other')], default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dispute',
            name='requested_resolution',
            field=models.CharField(choices=[('full_refund', 'Full Refund'), ('partial_refund', 'Partial Refund'), ('replacement', 'Replacement'), ('other', 'Other')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dispute',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispute',
            name='return_courier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dispute',
            name='return_received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispute',
            name='return_shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispute',
            name='return_tracking',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dispute',
            name='seller_courier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dispute',
            name='seller_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispute',
            name='seller_declaration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dispute',
            name='seller_delivery_confirm',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dispute',
            name='seller_responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispute',
            name='seller_ship_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispute',
            name='seller_tracking',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('awaiting_seller', 'Awaiting Seller Response'), ('awaiting_buyer', 'Awaiting Buyer Reply'), ('under_review', 'Under Admin Review'), ('more_info', 'More Information Requested'), ('return_required', 'Return Required'), ('return_shipped', 'Return Shipped'), ('return_received', 'Return Received'), ('resolved_buyer', 'Resolved - Buyer Won'), ('resolved_seller', 'Resolved - Seller Won'), ('resolved_mutual', 'Resolved - Mutual Agreement'), ('cancelled', 'Cancelled')], default='pending', max_length=30),
        ),
        migrations.CreateModel(
            name='DisputeEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='dispute_evidence/%Y/%m/%d/')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('pdf', 'PDF'), ('document', 'Document'), ('receipt', 'Receipt'), ('other', 'Other')], default='other', max_length=20)),
                ('uploaded_by', models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller')], max_length=10)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='Size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='multi.dispute')),
            ],
            options={
                'verbose_name_plural': 'Dispute Evidences',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DisputeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('admin', 'Admin')], max_length=10)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='multi.dispute')),
                ('sender_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
