# Generated by Django 5.2.15 on 2026-07-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi', '0022_orderitem_delivered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='seller_address_deadline',
            field=models.DateTimeField(blank=True, help_text='Deadline for seller to provide return address (6 days from admin decision)', null=True),
        ),
        migrations.AddField(
            model_name='dispute',
            name='seller_return_address',
            field=models.TextField(blank=True, help_text='Address where buyer should return the item', null=True),
        ),
        migrations.AddField(
            model_name='dispute',
            name='seller_return_address_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
