# Generated by Django 5.2.15 on 2026-07-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi', '0023_dispute_seller_address_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='return_not_received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispute',
            name='return_not_received_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
