# Generated by Django 5.2.15 on 2026-07-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi', '0024_dispute_return_not_received_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='warning_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
